version: 2.1

jobs:
  backend:
    docker:
      - image: cimg/base:2024.09
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run: |
          docker build -t udagram-api-user ./udagram-api-user
          docker build -t udagram-api-feed ./udagram-api-feed
      - run:
          command: |
            TAG=1.0.$TAG_NUMBER
            docker tag udagram-api-user $DOCKER_USERNAME/udagram-api-user:$TAG
            ocker tag udagram-api-feed $DOCKER_USERNAME/udagram-api-feed:$TAG
      - run:
          command: | 
            docker --version
            TAG=1.0.$TAG_NUMBER
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $DOCKER_USERNAME/udagram-api-user:$TAG
            docker push $DOCKER_USERNAME/udagram-api-feed:$TAG

workflows:
  version: 2
  backend-workflow:
    jobs:
      - backend




